src/Entity/FictionUserRating.php
<?php

namespace App\Entity;

use App\Utils\Math;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass="App\Repository\FictionUserRatingRepository")
 */
class FictionUserRating
{

    public const MIN_RATING = 1.0;
    public const MAX_RATING = 10.0;

    /**
     * @ORM\Id()
     * @ORM\ManyToOne(targetEntity="App\Entity\Fiction", inversedBy="ratings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $fiction;

    /**
     * @ORM\Id()
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="fictionRatings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     *
     * @ORM\Column(type="float", precision=1)
     */
    private $rating;

    /**
     * @ORM\Column(type="datetime")
     * @Gedmo\Timestampable(on="create")
     */
    private $ratedAt;

    public function __construct(Fiction $fiction, User $user, float $rating)
    {
        $this->fiction = $fiction;
        $this->user = $user;
        $this->rating = Math::clamp($rating, self::MIN_RATING, self::MAX_RATING);
    }

    public function getId(): string
    {
        return $this->fiction->getId() . '-' . $this->user->getId();
    }

    public function getFiction(): ?Fiction
    {
        return $this->fiction;
    }

    public function setFiction(?Fiction $fiction): self
    {
        $this->fiction = $fiction;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getRating(): ?float
    {
        return $this->rating;
    }

    public function setRating(int $rating): self
    {
        $this->rating = $rating;

        return $this;
    }

    public function getRatedAt(): ?\DateTimeInterface
    {
        return $this->ratedAt;
    }

    public function setRatedAt(\DateTimeInterface $ratedAt): self
    {
        $this->ratedAt = $ratedAt;

        return $this;
    }
}

templates/partials/_comment.html.twig
<li>{{ comment.author.username }} - {{ comment.body }}<br/>
    <small>{{ comment.createdAt|localizeddate }}</small>
</li>

templates/partials/_comments.html.twig
<ul>
    {% for comment in comments %}
        {% embed 'partials/_comment.html.twig' with {'comment': comment} %}{% endembed %}
        {% if comment.children.count > 0 %}
            {% embed 'partials/_comments.html.twig' with {'comments': comment.children} %}{% endembed %}
        {% endif %}
    {% endfor %}
</ul>

templates/partials/_flashbags.html.twig
{% for label, messages in app.flashes %}
    {% for message in messages %}
        {% if message is iterable %}
            {% set icon = message.icon|default(null) %}
            {% set translated = message.id|trans(message.parameters|default({}))|raw %}
        {% else %}
            {% set icon = null %}
            {% set translated = message|trans|raw %}
        {% endif %}
        <base-alert type="{{ label }}" dismissible>
            {% if icon %}
                <span class="alert-inner--icon">
                     <i class="{{ icon }}"></i>
                </span>
            {% endif %}
            {{ translated|raw }}
        </base-alert>
    {% endfor %}
{% endfor %}

templates/partials/_footer.html.twig
<footer>
    <div class="copyright">{{ sitename }} - {{ "now"|date('Y') }}</div>
    <div class="language-selector">
        {% include 'partials/_language_selector.html.twig' %}
    </div>
</footer>

templates/partials/_language_selector.html.twig
{% set route = app.request.attributes.get('_route') %}
                {% set route_params = app.request.attributes.get('_route_params') %}
                {% set params = route_params|merge(app.request.query.all) %}
<a href="{{ path(route, params|merge({_locale: 'fr'}))|regex_replace('/%5B\\d+/', '%5B') }}"
   class="badge {{ app.request.locale == 'fr' ? 'badge-secondary active' : 'badge-primary' }} language-picker">fr</a>
<a href="{{ path(route, params|merge({_locale: 'en'}))|regex_replace('/%5B\\d+/', '%5B') }}"
   class="badge {{ app.request.locale == 'en' ? 'badge-secondary active' : 'badge-primary' }} language-picker">en</a>

templates/partials/_navigation.html.twig
{% set links = [
    { name: 'global.navigation.fictions', path: path('fiction.index'), params: {} }
] %}
{% set backPathMap = {
    'fiction.index': path('homepage'),
    'fiction.show': path('fiction.index'),
} %}
{% set backPath = backPathMap[app.request.attributes.get('_route')] is defined ?
    backPathMap[app.request.attributes.get('_route')] :
    null
%}
{% set homepage = app.request.attributes.get('_route') == 'homepage' %}
{% set mobile = is_touch_device() %}
{% if app.user %}
    {% set links = links|merge([
        { name: 'global.navigation.profile', path: path('profile.me'), params: {'username': app.user.username}}
    ]) %}
    {% if is_granted('ROLE_ADMIN') %}
        {% set links = links|merge([
            { name: 'global.navigation.admin', path: path('admin.index'), params: {}}
        ]) %}
    {% endif %}
{% else %}
    {% set links = links|merge([
        { name: 'global.navigation.login', id: 'login', path: '#', params: {}},
        { name: 'global.navigation.register', path: path('registration'), params: {}}
    ]) %}
{% endif %}
{% if app.user %}
    {% set links = links|merge([
        { name: 'global.navigation.logout', path: path('logout'), params: {}}
    ]) %}
{% endif %}
<nav id="renderedNav" class="navbar main-navigation navbar-expand-lg navbar-dark bg-primary"
     style="box-shadow: 0 15px 35px rgba(50, 50, 93, 0.01), 0 5px 15px rgba(0, 0, 0, 0.05);">
    <div class="container">
        {% if mobile and not homepage %}
            <i class="fa fa-angle-left fa-2x back-icon"></i>
        {% endif %}
        <a href="{{ path('homepage') }}" class="navbar-brand">
            {{ sitename }}
        </a>
        {% if mobile %}
            <button type="button" class="navbar-toggler">
                <span class="navbar-toggler-icon" ></span>
            </button>
        {% endif %}
        <div class="collapse navbar-collapse">
            <div class="navbar-collapse-header"></div>
            <ul class="navbar-nav ml-lg-auto">
                {% for link in links %}
                    <li class="nav-item">
                        <a href="{{ link.path }}" class="nav-link">
                            {{ link.name|trans(link.params)|regex_replace('({|})', '') }}
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</nav>
<app-header
        :back-path="{{ backPath|json_encode }}"
        csrf-token="{{ csrf_token('authenticate') }}"
        sitename="{{ sitename }}"
        homepage="{{ path('homepage') }}"
        :links="{{ links|json_encode }}"></app-header>

templates/partials/_pagination.html.twig
{% set classes = classes|default([]) %}
{% set proximity = is_touch_device() ? 1 : 4 %}

{{ pagerfanta(for, 'noelfic_pagination', {proximity: proximity, routeParams: app.request.query.all, class: classes|join(' ')}) }}

templates/partials/_vue_data.html.twig
<script id="store">
    window.__USER = {{ app.user ? app.user|props|raw : 'null' }}
    window.__TOUCHDEVICE = {{ is_touch_device()|json_encode|raw }}
    window.__HOMEPAGE = {{ (app.request.attributes.get('_route') == 'homepage')|json_encode|raw }}
</script>